-- RAG evidence store. Run this in Supabase SQL Editor before uploading corpus rows.
create extension if not exists vector with schema extensions;

create table if not exists public.rag_chunks (
    id bigint generated by default as identity primary key,
    chunk_id text not null unique,
    doc_id text not null,
    path text not null,
    doc_type text not null,
    product text[] not null default '{}',
    issue_types text[] not null default '{}',
    source text not null,
    published_at date,
    effective_from date,
    effective_to date,
    page integer not null,
    section text,
    content text not null,
    embedding extensions.vector(768) not null,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists rag_chunks_embedding_hnsw_idx
    on public.rag_chunks using hnsw (embedding extensions.vector_cosine_ops);
create index if not exists rag_chunks_product_gin_idx
    on public.rag_chunks using gin (product);
create index if not exists rag_chunks_effective_idx
    on public.rag_chunks (effective_from, effective_to);
create index if not exists rag_chunks_doc_idx
    on public.rag_chunks (doc_id);

alter table public.rag_chunks enable row level security;
revoke all on table public.rag_chunks from anon, authenticated;
grant all on table public.rag_chunks to service_role;

create or replace function public.match_rag_chunks(
    query_embedding extensions.vector(768),
    match_count integer default 5,
    filter_product text default null,
    filter_as_of date default null
)
returns table (
    chunk_id text,
    doc_id text,
    path text,
    doc_type text,
    product text[],
    source text,
    published_at date,
    effective_from date,
    effective_to date,
    page integer,
    section text,
    content text,
    similarity double precision
)
language sql
stable
security definer
set search_path = public, extensions
as $$
    select
        c.chunk_id,
        c.doc_id,
        c.path,
        c.doc_type,
        c.product,
        c.source,
        c.published_at,
        c.effective_from,
        c.effective_to,
        c.page,
        c.section,
        c.content,
        1 - (c.embedding <=> query_embedding) as similarity
    from public.rag_chunks c
    where c.doc_type <> 'glossary'
      and (
          filter_product is null
          or filter_product = any(c.product)
          or '공통' = any(c.product)
      )
      and (
          filter_as_of is null
          or (c.effective_from is null or c.effective_from <= filter_as_of)
      )
      and (
          filter_as_of is null
          or (c.effective_to is null or c.effective_to >= filter_as_of)
      )
    order by c.embedding <=> query_embedding
    limit least(greatest(match_count, 1), 50);
$$;

revoke execute on function public.match_rag_chunks(extensions.vector(768), integer, text, date)
    from public, anon, authenticated;
grant execute on function public.match_rag_chunks(extensions.vector(768), integer, text, date)
    to service_role;
